# Generated by Django 6.0.2 on 2026-03-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antennas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yagiantenna',
            old_name='body',
            new_name='detail',
        ),
    ]
