# Generated by Django 6.0.2 on 2026-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antennas', '0002_rename_body_yagiantenna_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='yagiantenna',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yagi_images/'),
        ),
    ]
