# Generated by Django 6.0.2 on 2026-03-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antennas', '0003_yagiantenna_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yagiantenna',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
