# Generated by Django 6.0.3 on 2026-04-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antennas', '0004_alter_yagiantenna_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('yagi', 'Yagi'), ('dipole', 'Dipole'), ('spiral', 'Spiral')], max_length=20)),
                ('detail', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='YagiAntenna',
        ),
    ]
