# Generated by Django 6.0.3 on 2026-04-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antennas', '0005_antenna_delete_yagiantenna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='image',
            field=models.URLField(),
        ),
    ]
