# Generated by Django 6.0.3 on 2026-04-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antennas', '0006_alter_antenna_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
